<?php // ==== ICONS ==== //

// Request an SVG icon from the theme's main icon sheet
// SVG accessibility tips: http://www.sitepoint.com/tips-accessible-svg/
// @filter: pendrell_icon
if ( !function_exists( 'pendrell_icon' ) ) : function pendrell_icon( $icon = '', $title = '', $desc = '' ) {

  // Initialize variables
  $output = $aria = $class = $url = '';

  // Check for title and description and wrap them both in the appropriate markup
  if ( !empty( $title ) )
    $title = '<title id="title">' . esc_html( strip_tags( $title ) ) . '</title>';
  if ( !empty( $desc ) )
    $desc = '<desc id="desc">' . esc_html( strip_tags( $desc ) ) . '</desc>';

  // Set the ARIA attributes
  if ( !empty( $title ) && !empty( $desc ) ) {
    $aria = ' aria-labelledby="title desc"';
  } elseif ( !empty( $title ) ) {
    $aria = ' aria-labelledby="title"';
  } elseif ( !empty( $desc ) ) {
    $aria = ' aria-labelledby="desc"';
  }

  // Add a class matching the icon set prefix (anything before the hyphen)
  if ( strpos( $icon, '-' ) )
    $class .= ' icon-' . current( explode( '-', $icon ) );

  // Use an external icon sheet if a URL has been defined
  if ( PENDRELL_MODULE_ICONS_URL )
    $url = PENDRELL_MODULE_ICONS_URL;

  // Put it all together
  $output = '<svg class="icon' . $class . ' icon-' . $icon . '" role="img"' . $aria . '>' . $title . $desc . '<use xlink:href="' . $url . '#i-' . $icon . '" /></use></svg>';

  return apply_filters( 'pendrell_icon', $output );

} endif;



// In-line SVG icon sheet; inject the icons directly into the document
if ( !function_exists( 'pendrell_icon_sheet_inline' ) ) : function pendrell_icon_sheet_inline() {

  // Path to the icon sheet generated by Gulp and set in `functions-config.php`
  $file = PENDRELL_MODULE_ICONS_PATH;

  // Check if requested file exists; if not, return early
  if ( !file_exists( $file ) )
    return;

  // Retrieve the contents of the file and suppress error messages
  $icons = @file_get_contents( $file );

  // Add the icons to the page if something was found; note that your SVG file should be sanitized for in-line use
  if ( !empty( $icons ) )
    echo $icons;

} endif;
if ( PENDRELL_MODULE_ICONS_PATH && PENDRELL_MODULE_ICONS_URL === false )
  add_action( 'pendrell_body_before', 'pendrell_icon_sheet_inline' );



// Provision front-end with necessary path information for jQuery.iconize function to work
if ( !function_exists( 'pendrell_icon_script_vars' ) ) : function pendrell_icon_script_vars( $script_vars = array() ) {
  if ( PENDRELL_MODULE_ICONS_URL ) {
    $script_vars = array_merge( $script_vars, array(
      'iconsUrl' => PENDRELL_MODULE_ICONS_URL
    ) );
  }
  return $script_vars;
} endif;
add_filter( 'pendrell_script_vars', 'pendrell_icon_script_vars' );



// Add some icons to archive titles; @TODO: remove when testing complete
if ( !function_exists( 'pendrell_icon_archive_title' ) ) : function pendrell_icon_archive_title( $contents ) {
  if ( is_tax( 'post_format', 'post-format-image' ) )
    $contents = pendrell_icon( 'ion-image' ) . $contents;
  if ( is_tax( 'post_format', 'post-format-gallery' ) )
    $contents = pendrell_icon( 'ion-images' ) . $contents;
  return $contents;
} endif;
//add_filter( 'pendrell_archive_title', 'pendrell_icon_archive_title' );
